# compose-lab/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hello-batch'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['hello-batch:8081']
        labels:
          job: hello-batch

