apiVersion: batch/v1
kind: Job
metadata:
  name: hello-batch
spec:
  template:
    metadata:
      labels: { app: hello-batch }
      annotations:                       
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8081"
        prometheus.io/path:   "/actuator/prometheus"
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: 8081
